POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "testuser2",
  "email": "test2@example.com",
  "password": "password123"
}

{
  "username": "testuser2",
  "email": "test2@example.com",
  "refreshToken": null,
  "_id": "68b9159f0a64c1be79aded8b",
  "createdAt": "2025-09-04T04:29:19.123Z",
  "updatedAt": "2025-09-04T04:29:19.123Z",
  "__v": 0
}